baseURL = "https://qirh.gitgub.io/faisal"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Fasial"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
publishDir = "docs"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/


[author]
  name = "Fasial Aldlijan"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "Web Developer/Data Scientist"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/faisalaldilaijan"

  [[params.social]]
    name = "github"
    url = "https://github.com/aldilaff"

  [[params.social]]
    name = "email"
    url = "aldilaff@gmail.com"
